//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIARestApi
{
    using AIAUniversalApp.Shared.Helpers;
    using System;
    using System.Collections.Generic;

    public partial class Quote
    {
        public Quote()
        {
            this.Drivers = new HashSet<Driver>();
            this.Vehicles = new HashSet<Vehicle>();
        }

        public Quote(bool b)
        {
            this.Drivers = new HashSet<Driver>();
            this.Vehicles = new HashSet<Vehicle>();

            if (b)
            {
                State = String.Empty;
                PreviousCarrier = String.Empty;
                CustomerAddress = String.Empty;
                CustomerFirstName = String.Empty;
                CustomerLastName = String.Empty;
                CustomerPhone = String.Empty;
                CustomerSsn = String.Empty;
                AIAUserId = 2;

                CustomerDob = DateTime.Now;
                SubmissionTime = DateTime.Now;

                User = Helper.Get<AIAUser>(1);
            }
        }

        public long Id { get; set; }
        public int AIAUserId { get; set; }
        public decimal Price { get; set; }
        public bool Submitted{ get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public string State { get; set; }
        public bool MovingViolation { get; set; }
        public string PreviousCarrier { get; set; }
        public bool ClaimInLastFive { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerSsn { get; set; }
        public System.DateTime CustomerDob { get; set; }
        public bool ForceMultiDiscount { get; set; }

        public ICollection<Driver> Drivers { get; set; }
        public ICollection<Vehicle> Vehicles { get; set; }
        public AIAUser User { get; set; }
    }
}

