//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIARestApi
{
    using System;
    using System.Collections.Generic;

    public partial class Vehicle
    {
        public Vehicle()
        {}
        public Vehicle(long quoteId, long pDriverId)
        {
            this.Make = "Emp";
            this.CarModel = "Emp";
            this.Vin = "Emp";
            this.QuoteId = quoteId;
            DriverId = pDriverId;

        }

        public long Id { get; set; }
        public string Make { get; set; }
        public string CarModel { get; set; }
        public int Year { get; set; }
        public decimal Mileage { get; set; }
        public int CurrentValue { get; set; }
        public int DaysDrivenPerWeek { get; set; }
        public string Vin { get; set; }
        public decimal AnnualMiles { get; set; }
        public bool HasDaytimeRunningLights { get; set; }
        public bool HasAntilockBrakingSystem { get; set; }
        public bool PassiveRestraints { get; set; }
        public bool AntiTheft { get; set; }
        public bool ReduceUse { get; set; }
        public bool GarageDifferent { get; set; }
        public long QuoteId { get; set; }
        public decimal MilesDrivenToWork { get; set; }
        public long DriverId { get; set; }

        public Driver Primary_Driver { get; set; }
        public Quote Quote { get; set; }
    }
}