//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIADataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.Vehicles = new HashSet<Vehicle>();
            this.Drivers = new HashSet<Driver>();
        }
    
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
        public System.DateTime SubmissionTime { get; set; }
        public string State { get; set; }
        public bool MovingViolation { get; set; }
        public string PreviousCarrier { get; set; }
        public bool ClaimInLastFive { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerSsn { get; set; }
        public System.DateTime CustomerDob { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
