//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIADataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Scope { get; set; }
        public string State { get; set; }
        public decimal DiscountPercentage { get; set; }
    }
}
