//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIADataModels
{
    using System;
    
    public enum State : int
    {
        VT = 1,
        ME = 2,
        MA = 3,
        NH = 4,
        CT = 5,
        PA = 6,
        NY = 7,
        SC = 8,
        WV = 9,
        VA = 10
    }
}
