//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIADataModels
{
    using System;
    
    public enum Status : int
    {
        Approved = 1,
        Rejected = 2,
        Pending = 3
    }
}
