//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIADataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public System.Guid Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public decimal Mileage { get; set; }
        public int CurrentValue { get; set; }
        public int DaysDrivenPerWeek { get; set; }
        public string Vin { get; set; }
        public decimal AnnualMiles { get; set; }
        public bool HasDaytimeRunningLights { get; set; }
        public bool HasAntilockBrakingSystem { get; set; }
        public bool PassiveRestraints { get; set; }
        public bool AntiTheft { get; set; }
        public bool ReduceUse { get; set; }
        public bool GarageDifferent { get; set; }
        public System.Guid QuoteId { get; set; }
        public decimal MilesDrivenToWork { get; set; }
    
        public virtual Quote Quote { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
