//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIARestApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIADbEntities : DbContext
    {
        public AIADbEntities()
            : base("name=AIADbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<AIAUser> AIAUsers { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
