//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIARestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIAUser
    {
        public AIAUser()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CanUseSystem { get; set; }
        public string ApplicationUserId { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
